apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sse-event-system
data:
  ENVIRONMENT: "production"
  APP_NAME: "Online Event Registration System"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  COOKIE_SECURE: "true"
  ALLOWED_ORIGINS: "http://frontend-service.sse-event-system.svc.cluster.local,http://localhost:3000"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "event_registration_db"
