apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sse-event-system
  labels:
    app: frontend-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
  selector:
    app: frontend-web
